### ISSUE TITLE
GitMob handleResponse: "git config --get --global commit.template"

### ISSUE THREAD

**Issue by tomocrafter** [rkotze/git-mob#110] opened 2023-06-19 11:40 UTC
### Prerequisites

- [x] [Checked that your issue isn't already filed][git-mob issues]
- [x] Tried upgrading to the latest git-mob version (`npm i -g git-mob`)
- [x] Tried upgrading to the latest git version (`brew upgrade git` if installed with Homebrew/Linuxbrew)

[git-mob issues]: https://github.com/rkotze/git-mob/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description
If commit.template is not set on git, The `GitMob handleResponse: "git config --get --global commit.template" ` file is being created when ran the command.
https://github.com/rkotze/git-mob/blob/93ff1ab56768bec558612b0e8009b25d45c653a7/packages/git-mob-core/src/commands.js#L29

### Steps to Reproduce

1. make sure commit.template has not been set
2. run command normally

**Expected behavior:** [What you expect to happen]
Throw the error and abort operation, without creating the new file
**Actual behavior:** [What actually happens]
creates unfriendly file
**Reproduces how often:** [What percentage of the time does it reproduce?]
everytime ran command
### Versions

- operating system and version: Ubutnu 23.04
- git-mob version (`git-mob --version`): via latest vscode extension
- git version (`git --version`):git version 2.40.1

**Comment by rkotze** [comment] 2023-06-20 18:40
Hey @tomocrafter 

I was not able to reproduce the error. I've removed the `commit.template` from my git config can no file appears.

- Can you share which commands you run? like adding a co-author or just `git mob`.
- Is this via the VS Code extension? If so, what error message do you see printed in the console if any? [Open developer tools](https://stackoverflow.com/questions/30765782/what-is-the-use-of-the-developer-tools-in-vs-code)

**Comment by rkotze** [comment] 2023-07-19 18:54
Closed as there has been no further activity on this issue.

**Closed** 2023-07-19 18:53 UTC
